version: '2.1'
services:
  mongo:
    image: mongo:3.6-jessie
    # ports:
    #   - 27017:27017
  node:
    build: .
    ports:
     - "80:3000"
     - "9229:9229"
    environment:
     - NODE_ENV=development
     - MONGO_HOST=mongo
     - MONGO_PORT=27017
    links:
     - mongo
    depends_on:
     - mongo
    volumes:
     - .:/starter
     - /starter/node_modules
